input_string1 = input("이름을 입력하세요: ")
input_string2 = input("학번을 입력하세요: ")
input_string3 = input("학과를 입력하세요: ")
print(f"<출력>\n이름: {input_string1} \n학번: {input_string2} \n 학과: {input_string3}")
print ("Hello World!")